Fix #173: use user library to avoid sudo
mork-optimization/mork pull request #186
Opened 2023-06-12 17:03 UTC by rmartinsanta

Fix #173: use user library to avoid sudo usage when installing R packages

2023-06-12 17:04 UTC, rmartinsanta commented
@isaaclo97, could you verify if it solves the requirement to use sudo on first run?

2023-06-14 09:21 UTC, isaaclo97 commented
I uninstall R and install it again.
It seems to work but i cannot check it since new error appear.

```
[2m[09:18:07][0;39m [31mERROR[0;39m [36m.[.[.[.[dispatcherServlet][0;39m [2m:[0;39m Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalArgumentException: Invalid integration key, got dTzQpg6vE6akz4w/x6cQ8A==] with root cause
java.lang.IllegalArgumentException: Invalid integration key, got dTzQpg6vE6akz4w/x6cQ8A==
	at es.urjc.etsii.grafo.autoconfig.controller.ExecutionController.validateAndPrepare(ExecutionController.java:88)
	at es.urjc.etsii.grafo.autoconfig.controller.ExecutionController.execute(ExecutionController.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
[2m[09:18:07][0;39m [32mINFO [0;39m [36me.u.e.g.a.i.r.RLangRunner [0;39m [2m:[0;39m # 2023-06-14 09:18:07 UTC: DONE (testConfig1) Elapsed wall-clock seconds: 0.19
[2m[09:18:07][0;39m [32mINFO [0;39m [36me.u.e.g.a.i.r.RLangRunner [0;39m [2m:[0;39m {"timestamp":"2023-06-14T09:18:07.012+00:00","status":500,"error":"Internal Server Error","path":"/execute"}
[2m[09:18:07][0;39m [32mINFO [0;39m [36me.u.e.g.a.i.r.RLangRunner [0;39m [2m:[0;39m 
[2m[09:18:07][0;39m [32mINFO [0;39m [36me.u.e.g.a.i.r.RLangRunner [0;39m [2m:[0;39m # Error occurred while executing targetRunner:
[2m[09:18:07][0;39m [32mINFO [0;39m [36me.u.e.g.a.i.r.RLangRunner [0;39m [2m:[0;39m == irace == The output of targetRunner should not be more than two numbers!
```

2023-06-14 09:46 UTC, isaaclo97 commented
> I uninstall R and install it again. It seems to work but i cannot check it since new error appear.
> 
> ```
> �[2m[09:18:07]�[0;39m �[31mERROR�[0;39m �[36m.[.[.[.[dispatcherServlet]�[0;39m �[2m:�[0;39m Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalArgumentException: Invalid integration key, got dTzQpg6vE6akz4w/x6cQ8A==] with root cause
> java.lang.IllegalArgumentException: Invalid integration key, got dTzQpg6vE6akz4w/x6cQ8A==
> 	at es.urjc.etsii.grafo.autoconfig.controller.ExecutionController.validateAndPrepare(ExecutionController.java:88)
> 	at es.urjc.etsii.grafo.autoconfig.controller.ExecutionController.execute(ExecutionController.java:62)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
> 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
> 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
> 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m # 2023-06-14 09:18:07 UTC: DONE (testConfig1) Elapsed wall-clock seconds: 0.19
> �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m {"timestamp":"2023-06-14T09:18:07.012+00:00","status":500,"error":"Internal Server Error","path":"/execute"}
> �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m 
> �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m # Error occurred while executing targetRunner:
> �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m == irace == The output of targetRunner should not be more than two numbers!
> ```

The problem it is related to non-updated scenario.txt and runner.R.

Maybe in runner.R can be checked if it is the correct file?

There are some erros installing it without sudo.

Without sudo:
```
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : Installing package into ‘/usr/local/lib/R/site-library’
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : (as ‘lib’ is unspecified)
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : Warning in install.packages("httr", type = "source", repos = "http://cran.us.r-project.org") :
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  :   'lib = "/usr/local/lib/R/site-library"' is not writable
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : Error in install.packages("httr", type = "source", repos = "http://cran.us.r-project.org") :
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  :   unable to install packages
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : In addition: Warning message:
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  :   there is no package called ‘httr’
[09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : Execution halted
```
With sudo:
```
[09:39:28] WARN  e.u.e.g.a.i.r.RLangRunner  : using C compiler: ‘gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0’
[09:39:28] WARN  e.u.e.g.a.i.r.RLangRunner  : installing to /usr/local/lib/R/site-library/00LOCK-askpass/00new/askpass/libs
[09:39:28] WARN  e.u.e.g.a.i.r.RLangRunner  :  R
[09:39:28] WARN  e.u.e.g.a.i.r.RLangRunner  :  inst
[09:39:28] WARN  e.u.e.g.a.i.r.RLangRunner  :  byte-compile and prepare package for lazy loading
[09:39:2 [...]

2023-06-14 10:21 UTC, isaaclo97 commented
> > I uninstall R and install it again. It seems to work but i cannot check it since new error appear.
> > ```
> > �[2m[09:18:07]�[0;39m �[31mERROR�[0;39m �[36m.[.[.[.[dispatcherServlet]�[0;39m �[2m:�[0;39m Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalArgumentException: Invalid integration key, got dTzQpg6vE6akz4w/x6cQ8A==] with root cause
> > java.lang.IllegalArgumentException: Invalid integration key, got dTzQpg6vE6akz4w/x6cQ8A==
> > 	at es.urjc.etsii.grafo.autoconfig.controller.ExecutionController.validateAndPrepare(ExecutionController.java:88)
> > 	at es.urjc.etsii.grafo.autoconfig.controller.ExecutionController.execute(ExecutionController.java:62)
> > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> > 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
> > 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
> > 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
> > 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
> > 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
> > 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> > 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
> > 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
> > 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
> > 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
> > 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
> > 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
> > 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
> > 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
> > 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> > 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
> > 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
> > 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> > 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
> > 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
> > 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
> > 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> > 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
> > 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
> > 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
> > 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> > 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
> > 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
> > 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
> > 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
> > 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
> > 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
> > 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
> > 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
> > 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
> > 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> > 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
> > 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
> > 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
> > 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
> > 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
> > 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
> > 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> > 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> > 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> > 	at java.base/java.lang.Thread.run(Thread.java:833)
> > �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m # 2023-06-14 09:18:07 UTC: DONE (testConfig1) Elapsed wall-clock seconds: 0.19
> > �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m {"timestamp":"2023-06-14T09:18:07.012+00:00","status":500,"error":"Internal Server Error","path":"/execute"}
> > �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m 
> > �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m # Error occurred while executing targetRunner:
> > �[2m[09:18:07]�[0;39m �[32mINFO �[0;39m �[36me.u.e.g.a.i.r.RLangRunner �[0;39m �[2m:�[0;39m == irace == The output of targetRunner should not be more than two numbers!
> > ```
> 
> The problem it is related to non-updated scenario.txt and runner.R.
> 
> Maybe in runner.R can be checked if it is the correct file?
> 
> There are some erros installing it without sudo.
> 
> Without sudo:
> 
> ```
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : Installing package into ‘/usr/local/lib/R/site-library’
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : (as ‘lib’ is unspecified)
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : Warning in install.packages("httr", type = "source", repos = "http://cran.us.r-project.org") :
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  :   'lib = "/usr/local/lib/R/site-library"' is not writable
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : Error in install.packages("httr", type = "source", repos = "http://cran.us.r-project.org") :
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  :   unable to install packages
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : In addition: Warning message:
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  :   there is no package called ‘httr’
> [09:37:46] WARN  e.u.e.g.a.i.r.RLangRunner  : Execution halted
> ```
> 
> With sudo:
> 
> ```
> [09:39:28] WARN  e.u.e.g.a.i.r.RLangRunner  : using C compiler: ‘gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0’
> [09:39:28] WARN  e.u.e.g.a.i.r.RLangRunner  : installing to /usr/local/lib/R/site-library/00LOCK-askpass/00new/askpass/libs
> [09:39:28] WARN  e.u.e.g.a [...]

2023-06-14 10:23 UTC, isaaclo97 requested changes
- Documentation about possible libraries requiered as: libcurl4-openssl-dev, opensll, curl, etc.
- Review the code, still require sudo in the first run of mork with autoconfig.

2023-06-14 11:29 UTC, rmartinsanta commented
sudo is not required if libcurl and openssl libs are already installed, I think the best approach would be to properly document it so the users installs them in Linux beforehand, using their package manager.

2023-06-14 11:32 UTC, rmartinsanta commented
Integration test with irace passed https://github.com/mork-optimization/mork/actions/runs/5266496172/jobs/9520493463?pr=186#step:7:968

2023-06-14 11:33 UTC, merged